/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\model\Projector.glb 
Author: dudecon (https://sketchfab.com/dudecon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-delta-squad-advisor-hologram-projector-e4a6d8f4bf4f4b86a6e7db50f6d49fcb
Title: Star Wars Delta Squad Advisor Hologram Projector
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Projector(props) {
  const { nodes, materials } = useGLTF('/model/Projector.glb')
  return (
    <group {...props} dispose={null} scale={0.06}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Brass} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Dark_Brass} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Teal_Glow} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.White_Glow} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.silver} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Brass} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Brass} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.silver} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/Projector.glb')
