// "use client";
// import type { Metadata } from "next";
// // import localFont from "next/font/local";
// import "./globals.css";
// import { ThemeProvider } from "@/components/ui/theme-provider";
// import { Syne } from 'next/font/google';
// import LoadingScreen from "@/components/Nav/LoadingScreen"; // Adjust the path as necessary
// import { useEffect, useState } from "react";
// import CustomCursor from "@/components/Nav/CustomCursor";

// export const syne_init = Syne({
//   subsets: ['latin'],
//   weight: ['800','400','700'], 
//   variable:'--font-syne',
// });

// // const geistSans = localFont({
// //   src: "./fonts/GeistVF.woff",
// //   variable: "--font-geist-sans",
// //   weight: "100 900",
// // });
// // const geistMono = localFont({
// //   src: "./fonts/GeistMonoVF.woff",
// //   variable: "--font-geist-mono",
// //   weight: "100 900",
// // });

// const metadata: Metadata = {
//   title: "Anshul Goswami",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const [isLoading, setIsLoading] = useState(true);

//   useEffect(() => {
//     const timer = setTimeout(() => {
//       setIsLoading(false);
//     }, 3000); // Set loading duration here (3 seconds)

//     return () => clearTimeout(timer);
//   }, []);

//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={`} ${syne_init.variable} antialiased `}>
//       {/* ${geistSans.variable} ${geistMono.variable */}
//         <CustomCursor />
//         <ThemeProvider attribute="class"
//             defaultTheme="dark"
//             enableSystem
//             disableTransitionOnChange>
//           {isLoading ? <LoadingScreen /> : children}
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
"use client";
import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Syne } from 'next/font/google';
import LoadingScreen from "@/components/Nav/LoadingScreen"; // Adjust the path as necessary
import { useLayoutEffect, useState } from "react";
import CustomCursor from "@/components/Nav/CustomCursor";

export const syne_init = Syne({
  subsets: ['latin'],
  weight: ['800','400','700'], 
  variable: '--font-syne',
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const metadata: Metadata = {
  title: "Anshul Goswami",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoading, setIsLoading] = useState(true);

  useLayoutEffect(() => {
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 3000); // Set loading duration here (3 seconds)

    return () => clearTimeout(timer);
  }, []);

  return (
    <html lang="en" className="
    !scroll-smooth" suppressHydrationWarning>
      <body className={` ${syne_init.variable} antialiased `}>
      {/* ${geistSans.variable} ${geistMono.variable} */}
        <CustomCursor />
        <ThemeProvider 
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {isLoading ? <LoadingScreen /> : children}
        </ThemeProvider>
      </body>
    </html>
  );
}
