"use client";
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Syne } from "next/font/google";
import LoadingScreen from "@/components/Nav/LoadingScreen";
import { useLayoutEffect, useState } from "react";
import CustomCursor from "@/components/Nav/CustomCursor";

export const syne_init = Syne({
  subsets: ["latin"],
  weight: ["800", "400", "700"],
  variable: "--font-syne",
});

const metadata: Metadata = {
  title: "Anshul Goswami",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoading, setIsLoading] = useState(true);

  useLayoutEffect(() => {
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 3000);

    return () => clearTimeout(timer);
  }, []);

  return (
    <html
      lang="en"
      className="!scroll-smooth"
      suppressHydrationWarning
    >
      <head>
        {/* Favicon links */}
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="icon" type="image/png" href="/favicon.png" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body className={`${syne_init.variable} antialiased`}>
        <CustomCursor />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {isLoading ? <LoadingScreen /> : children}
        </ThemeProvider>
      </body>
    </html>
  );
}
